question_data = [{"category": "Vehicles", "type": "boolean", "difficulty": "hard",
                  "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Vatican City is a country.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The Japanese Shinkansen beat the French TGV&#039;s speed record for fastest electric rail train.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;Kamea,&quot; the Gilbertese Islander word for dog, is derived from the English phrase &quot;Come here!&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
                  "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Bulls are attracted to the color red.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "Tennis was once known as Racquetball.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                  "question": "The Xenomorph from the science fiction film &quot;Alien&quot; has acidic blood.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                  "question": "An atom contains a nucleus.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Ottawa is the capital of Canada.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "There are no deserts in Europe.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
                  "question": "The Angry Video Game Nerd&#039;s alter ego is &quot;Board James&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "DHCP stands for Dynamic Host Configuration Port.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The capital of the US State Ohio is the city of Chillicothe.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Liechtenstein does not have an airport.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In the video game &quot;Transistor&quot;, &quot;Red&quot; is the name of the main character.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "A &#039;Millinillion&#039; is a real number.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Sugar contains fat.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
                  "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Call Of Duty: Zombies&quot;, you can upgrade the &quot;Apothicon Servant&quot; in the &quot;Shadows Of Evil&quot; map.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                  "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Star Trek: The Next Generation&quot;, Data is the only android in existence.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States of America was the first country to launch a man into space.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "hard",
                  "question": "Janus was the Roman god of doorways and passageways.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "An isosceles triangle has two sides of equal length as opposed to three.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "An equilateral triangle always has every angle measuring 60&deg;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "A pasodoble is a type of Italian pasta sauce.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Rabbits are carnivores.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Minecraft wasn&rsquo;t the original name to Minecraft.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "The Paradox Interactive game &quot;Stellaris&quot; was released in 2016.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                  "question": "The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Musicals & Theatres", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The protagonist&#039;s names in &#039;Who&#039;s Afraid of Virginia Woolf&#039;, George and Martha, were derived from George Washington and his wife.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
